---
title: "data_wrangling_II"
author: "David"
date: "2024-10-10"
output: html_document
---
```{r}
library(tidyverse)
library(rvest)
library(httr)

```


```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

Get things I actually want

```{r}
major_use_df =
  drug_use_html |>
  html_table() |>
  first() |>
  slice(-1)

```

exercise

```{r}
url = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
best_place = read_html(url)
cost_of_living =
  best_place |>
  html_table(header = TRUE) |>
  first()

```


```{r}
swm_html = read_html("https://www.imdb.com/list/ls070150896/")

title_vec =
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

metascore_vec =
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)

```


```{r}
books_html = read_html("http://books.toscrape.com/")

book_name =
  books_html |>
  html_elements("h3") |>
  html_text2()

book_star =
  books_html |>
  html_elements(".star-rating") |>
  html_attr("class")
  
book_price = 
  books_html |>
  html_elements(".price_color") |>
  html_text() 

books = tibble(
  title = book_name,
  stars = book_star,
  price = book_price
)

```

use API
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |>
  content()

```


```{r}
brfss_df =
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |>
  content()
```


```{r}
poke =
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |>
  content()

poke$height
poke$abilities
```
